[workspace]
name = "ft-filter"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = ">=3.10"
fasttext = ">=0.9.2"
datasets = ">=2.18.0"

[tasks]
build-release = "cargo build --release"
test-unit = "cargo test"
bench = { cmd = "python tests/benchmark.py", depends-on = ["build-release"] }
test-parity = { cmd = "python tests/verify_parity.py", depends-on = ["build-release"] }
test-fineweb = { cmd = "python tests/verify_fineweb.py", depends-on = ["build-release"] }
